resources:
- manager.yaml
- scheduler.yaml
- scheduler-config.yaml
- descheduler.yaml
- descheduler-config.yaml
- koordlet.yaml
- koord-batch.yaml
- koord-free.yaml
- koord-mid.yaml
- koord-prod.yaml
- slo-controller-config.yaml

generatorOptions:
  disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: descheduler
  newName: acejilam/desc
  newTag: v1
- name: koordlet
  newName: acejilam/koordlet
  newTag: v1
- name: manager
  newName: acejilam/manager
  newTag: v1
- name: scheduler
  newName: acejilam/sc
  newTag: v1
