apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: gang-example
  namespace: default
  annotations:
    "gang.scheduling.koordinator.sh/total-number": "10"
#    "gang.scheduling.koordinator.sh/timeout": "3000"
#    "gang.scheduling.koordinator.sh/mode": "Strict、NonStrict"
#    "gang.scheduling.koordinator.sh/match-policy": "once-satisfied、only-waiting、waiting-and-running"
#    "gang.scheduling.koordinator.sh/groups": '["a"]'  # 会填充自己
spec:
  scheduleTimeoutSeconds: 10
  minMember: 2