apiVersion: kubescheduler.config.k8s.io/v1beta2                                                      #
kind: KubeSchedulerConfiguration                                                                     #
leaderElection:                                                                                      #
  leaderElect: true                                                                                  #
  resourceLock: leases                                                                               #
  resourceName: koord-scheduler                                                                      #
  resourceNamespace: koordinator-system                                                              #
profiles:                                                                                            #
  - pluginConfig:                                                                                    #
    - name: NodeResourcesFit                                                                         #
      args:                                                                                          #
        apiVersion: kubescheduler.config.k8s.io/v1beta2                                              #
        kind: NodeResourcesFitArgs                                                                   #
        scoringStrategy:                                                                             #
          type: LeastAllocated                                                                       #
          resources:                                                                                 #
            - name: cpu                                                                              #
              weight: 1                                                                              #
            - name: memory                                                                           #
              weight: 1                                                                              #
            - name: "kubernetes.io/batch-cpu"                                                        #
              weight: 1                                                                              #
            - name: "kubernetes.io/batch-memory"                                                     #
              weight: 1                                                                              #
    - name: LoadAwareScheduling                                                                      #
      args:                                                                                          #
        apiVersion: kubescheduler.config.k8s.io/v1beta2                                              #
        kind: LoadAwareSchedulingArgs                                                                #
        filterExpiredNodeMetrics: true                                                               #
        nodeMetricExpirationSeconds: 180                                                             #
        resourceWeights:                                                                             #
          cpu: 1                                                                                     #
          memory: 1                                                                                  #
        usageThresholds:                                                                             #
          cpu: 65                                                                                    #
          memory: 95                                                                                 #
        prodUsageThresholds:                                                                         #
           cpu: 55                                                                                   #
           memory: 75                                                                                #
        scoreAccordingProdUsage: true                                                                #
        aggregated:                                                                                  #
           usageThresholds:                                                                          #
             cpu: 65                                                                                 #
             memory: 95                                                                              #
           usageAggregationType: "p95"                                                               #
           scoreAggregationType: "p95"                                                               #
        estimatedScalingFactors:                                                                     #
          cpu: 85                                                                                    #
          memory: 70                                                                                 #
    - name: ElasticQuota                                                                             #
      args:                                                                                          #
        apiVersion: kubescheduler.config.k8s.io/v1beta2                                              #
        kind: ElasticQuotaArgs                                                                       #
        quotaGroupNamespace: koordinator-system                                                      #
        enableCheckParentQuota: true                                                                 #
        monitorAllQuotas: true                                                                       #
        revokePodInterval: 60s                                                                       #
        delayEvictTime: 300s                                                                         #
    - name: Reservation                                                                              #
      args:                                                                                          #
          apiVersion: kubescheduler.config.k8s.io/v1beta2                                            #
          kind: ReservationArgs                                                                      #
          enablePreemption: true                                                                     # 无用

    - name: Coscheduling                                                                              #
      args:                                                                                          #
          apiVersion: kubescheduler.config.k8s.io/v1beta2                                            #
          kind: CoschedulingArgs                                                                      #
          defaultTimeout: "30s"                                                                     # 无用
          controllerWorkers: 1                                                                    # 无用
          skipCheckScheduleCycle: "false"                                                                     # 无用




    - name: DeviceShare                                                                          #
      args:                                                                                          #
          apiVersion: kubescheduler.config.k8s.io/v1beta2                                            #
          kind: DeviceShareArgs                                                                      #
          allocator: ""
          scoringStrategy:
            type: "LeastAllocatedd"
            resources:
              - name: "cpu"
                weight: 22
    plugins:                                                                                         #
      queueSort:                                                                                     #
        disabled:                                                                                    #
          - name: "*"                                                                                #
        enabled:                                                                                     #
          - name: Coscheduling                                                                       #
      preFilter:                                                                                     #
        enabled:                                                                                     #
          - name: Reservation                                                                        #
          - name: NodeNUMAResource                                                                   #
          - name: DeviceShare                                                                        #
          - name: Coscheduling                                                                       #
          - name: ElasticQuota                                                                       #
      filter:                                                                                        #
        enabled:                                                                                     #
          - name: LoadAwareScheduling                                                                #
          - name: NodeNUMAResource                                                                   #
          - name: DeviceShare                                                                        #
          - name: Reservation                                                                        #
      postFilter:                                                                                    #
        disabled:                                                                                    #
          - name: "*"                                                                                #
        enabled:                                                                                     #
          - name: Reservation                                                                        #
          - name: Coscheduling                                                                       #
          - name: ElasticQuota                                                                       #
          - name: DefaultPreemption                                                                  #
      preScore:                                                                                      #
        enabled:                                                                                     #
          - name: Reservation # The Reservation plugin must come first                               #
      score:                                                                                         #
        enabled:                                                                                     #
          - name: LoadAwareScheduling                                                                #
            weight: 1                                                                                #
          - name: NodeNUMAResource                                                                   #
            weight: 1                                                                                #
          - name: DeviceShare                                                                        #
            weight: 1                                                                                #
          - name: Reservation                                                                        #
            weight: 5000                                                                             #
      reserve:                                                                                       #
        enabled:                                                                                     #
          - name: Reservation # The Reservation plugin must come first                               #
          - name: LoadAwareScheduling                                                                #
          - name: NodeNUMAResource                                                                   #
          - name: DeviceShare                                                                        #
          - name: Coscheduling                                                                       #
          - name: ElasticQuota                                                                       #
      permit:                                                                                        #
        enabled:                                                                                     #
          - name: Coscheduling                                                                       #
      preBind:                                                                                       #
        enabled:                                                                                     #
          - name: NodeNUMAResource                                                                   #
          - name: DeviceShare                                                                        #
          - name: Reservation                                                                        #
          - name: DefaultPreBind                                                                     #
      bind:                                                                                          #
        disabled:                                                                                    #
          - name: "*"                                                                                #
        enabled:                                                                                     #
          - name: Reservation                                                                        #
          - name: DefaultBinder                                                                      #
      postBind:                                                                                      #
        enabled:                                                                                     #
          - name: Coscheduling                                                                       #
#    PluginConfig:                                                                                   #
#      - name: NodeResourcesFit                                                                      #
#        args:                                                                                       #
#          IgnoredResources:                                                                         #
#            - cpu // 会添加到这里🦠                                                                        #
#          IgnoredResourceGroups:                                                                    #
#          ScoringStrategy:                                                                          #
#            Type:                                                                                   #
#            Resources:                                                                              #
#              - Name:                                                                               #
#                Weight:                                                                             #
#            RequestedToCapacityRatio:                                                               #
#              Shape:                                                                                #
#                - Utilization:                                                                      #
#                  Score:                                                                            #
                                                                                                     #
    schedulerName: koord-scheduler                                                                   #
#extenders:                                                                                          #
#  - managedResources:                                                                               #
#      - name: cpu                                                                                   #
#        ignoredByScheduler: true   // true会添加🦠                                                      #
#    HTTPTimeout: 30                                                                                 #
#    TLSConfig:                                                                                      #
#      Insecure: false                                                                               #
#      ServerName:                                                                                   #
#      CertFile:                                                                                     #
#    EnableHTTPS:                                                                                    #
#    Ignorable:                                                                                      #
                                                                                                     #
enableProfiling: true                                                                                #
clientConnection:                                                                                    #
#  kubeconfig: "/Users/acejilam/.kube/172.16.244.143.config"                                          #
  kubeconfig: "/Users/acejilam/.kube/config"